services:
  postgres:
    image: postgres:17.6
    container_name: webhook-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: webhook
      POSTGRES_DB: webhook
    ports:
      - "2003:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.4
    container_name: webhook-redis
    restart: always
    ports:
      - "5099:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
